/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { SheetProvider } from '@/providers/sheet-providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'HexaCommerce',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang="pt-BR">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <SessionProvider session={session}>
          {children}
          <SheetProvider />
        </SessionProvider>
      </body>
    </html>
  )
}
